### ISSUE TITLE
SignUpNicknameVC URL 생성관련 이슈

### ISSUE THREAD

**Issue by asong57** [JNU-econovation/EggMeet#103]
다른 화면에서 URL을 생성할 때에는 아무 문제가 없었는데 SignUpNicknameVC에서 URL을 생성하는 부분에서 계속 " Unexpectedly found nil while unwrapping an Optional value"가 발생합니다.
이런저런 방법들을 다 해보았는데 계속 같은 오류가 발생하여 일단 다른 파트 작업을 하고 돌아오겠습니다...

**Comment by yunseong76039287** [comment]
소스코드 커밋해주실 수 있나요?

**Comment by asong57** [comment]
어젯밤부터 계속 신경썼었는데 알고보니 URL 안에 한글을 그대로 넣어서 URL이 제대로 생성되지 않는 문제였습니다...
URL에 들어가는 한글을 인코딩해서 넣으면 되는 것 같아요!

**Comment by asong57** [comment]
https://jintaewoo.tistory.com/31
참고 블로그입니다!
