### ISSUE TITLE
SignUpIntroducePopUpView NSException

### ISSUE THREAD

**Issue by yunseong76039287** [JNU-econovation/EggMeet#38]
SignUpIntroducePopUpView 에서 `어떻게 적어야 할지 모르겠다면 이런 내용은 어때요?` 를 터치하면
에러가 발생하며 시뮬레이터가 종료됩니다.
`this class is not key value coding-compliant for the key closeButton` 에러가 뜹니다.
디렉토리 구조를 변경하던 도중, 발생한 에러인 줄 알고 `git reset --hard` 를 통해 이전 커밋으로 돌렸는데도 오류가 발생하고
프로젝트 파일을 지우고 다시 저장소를 생성했는데도 오류가 발생합니다.
혹시 제가 디렉토리 구조를 변경하면서 발생한 오류일 수도 있으니, 각자 로컬에서 확인 한번씩 부탁드립니다.

**Comment by asong57** [comment]
Main 스토리보드에서 SignUpIntroducePopUpView가 클래스 이름인 SignUpIntroducePopUpVC으로 설정되어 있지 않아서 발생한 오류였습니다. 클래스명 잘 설정했더니 오류 발생 없이 팝업화면 나타납니다.
