### ISSUE TITLE
탭바가 화면 이동을 하고 나면 사라지는 이슈

### ISSUE THREAD

**Issue by asong57** [JNU-econovation/EggMeet#61]
탭바가 구성되어 있는 홈화면에서 필터VC로 이동했다가 다시 홈VC로 돌아오면 홈화면의 탭바가 사라지는 문제가 발생합니다.

**Comment by yunseong76039287** [comment]
아마도 unwind Segue를 사용하지 않아서 생긴 문제인 것 같습니다. 한번 unwind Segue를 사용해서 해결해보세요.
https://nsios.tistory.com/29
